# Week 2: Introduction to Python vectorisation

In [1]:
import numpy as np
import time

## 1. Vectorisation timing

In [8]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

#measures the current time
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorised version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop: " + str(1000*(toc-tic))+ "ms")

250171.62950282387
Vectorised version: 1.1150836944580078ms
250171.62950282157
For loop: 617.4798011779785ms


## 2. Python broadcasting

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# sum vertically
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100*(A/cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
# 1x 4 matrix
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

## 3. Numpy vectors

In [9]:
a = np.random.randn(5)
print(a)

[-0.21718752 -0.40991284  1.01074214 -0.27251175  0.64050618]


In [10]:
# a is rank 1 array
# in python is nether a row vector or a col vector
print(a.shape)

(5,)


In [11]:
# it is the same as a
print(a.T)

[-0.21718752 -0.40991284  1.01074214 -0.27251175  0.64050618]


In coding network, not recommended to use rank 1 array.

In [13]:
# should do instead
b = np.random.rand(5,1)
print(b)

[[0.7805679 ]
 [0.02291761]
 [0.28258959]
 [0.19139803]
 [0.88286311]]


In [14]:
print(b.T)

[[0.7805679  0.02291761 0.28258959 0.19139803 0.88286311]]


In [15]:
print(np.dot(b,b.T))

[[6.09286239e-01 1.78887505e-02 2.20580363e-01 1.49399154e-01
  6.89134602e-01]
 [1.78887505e-02 5.25216840e-04 6.47627801e-03 4.38638526e-03
  2.02331123e-02]
 [2.20580363e-01 6.47627801e-03 7.98568776e-02 5.40870899e-02
  2.49487927e-01]
 [1.49399154e-01 4.38638526e-03 5.40870899e-02 3.66332041e-02
  1.68978256e-01]
 [6.89134602e-01 2.02331123e-02 2.49487927e-01 1.68978256e-01
  7.79447277e-01]]
